on:
  pull_request:
    branches:
      - main

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        id: trigger-circleci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          # CircleCI-Public/trigger-circleci-pipeline-action expects CCI_TOKEN
          CCI_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
